config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/island", to: 'pages#island'
  get "/robot", to: 'pages#robot'
  get "/planet", to: 'pages#planet'
  get "/bottle", to: 'pages#bottle'
  get "/uploader", to: 'pages#uploader'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home

  end

  def planet
  end

  def robot
  end

  def island
  end

  def bottle
  end

  def uploader
    file_path = "../../../Desktop/Blender/objets/bouteille_augmented.glb"
    Cloudinary::Uploader.upload(file_path, use_filename: true, resource_type: :raw)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AugmentedTests</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
     <!-- we import arjs version without NFT but with marker + location based support -->
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>

  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/bottle.html.erb
<a-scene embedded arjs renderer="logarithmicDepthBuffer: true;">

  <a-assets>
    <a-asset-item id="bottle" src="<%= cloudinary_url("bouteille_augmented_j8e1xa.glb",resource_type: :raw) %>"></a-asset-item>
  </a-assets>

  <a-marker preset="hiro">

    <a-entity
      position="0 0 0"
      scale="1 1 1"
      gltf-model="#bottle"
    ></a-entity>

  <a-entity light="type: point; intensity: 8; distance: 50; decay: 2"
    position="0 1 10"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 8; distance: 50; decay: 2"
    position="-5 1 -10"></a-entity>  </a-marker>
  <a-entity camera></a-entity>

<!--   <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 -10"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="10 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="-10 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity> -->
</a-scene>

app/views/pages/home.html.erb
<div class="tim-container">
  <ul>
    <li><%= link_to "ROBOT", robot_path %></li>
    <li><%= link_to "PLANET", planet_path %></li>
    <li><%= link_to "ISLAND", island_path %></li>
    <li><%= link_to "BOTTLE", bottle_path %></li>
  </ul>
</div>

app/views/pages/island.html.erb
<a-scene embedded arjs>
  <a-marker preset="hiro">
    <a-entity
      position="0 0 0"
      scale="0.6 0.6 0.6"
      gltf-model="<%= cloudinary_url("floating_island_svegdv.glb",resource_type: :raw) %>"
    ></a-entity>

  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 -4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="-4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
</a-scene>

app/views/pages/planet.html.erb
<a-scene embedded arjs>
  <a-marker preset="hiro">
    <a-entity
      position="0 0 0"
      scale="0.6 0.6 0.6"
      gltf-model="<%= cloudinary_url("planet_qn0kzv.glb",resource_type: :raw) %>"
      rotation="0 0 0" animation="property: rotation; to: 0 360 0; loop: true; dur: 10000"
    ></a-entity>

  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 -4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="-4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
</a-scene>

app/views/pages/robot.html.erb
<a-scene embedded arjs>
  <a-marker preset="hiro">
    <a-entity
      position="0 0 0"
      scale="0.6 0.6 0.6"
      gltf-model="<%= cloudinary_url("robot_project_texture_paint_xpdyub.glb",resource_type: :raw) %>"
    ></a-entity>

  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="0 1 -4"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
  <a-entity light="type: point; intensity: 10; distance: 50; decay: 2"
    position="-4 1 0"></a-entity>  </a-marker>
  <a-entity camera></a-entity>
</a-scene>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>